<a href="https://colab.research.google.com/github/SharovarovAleksandr/Academy/blob/main/Lesson52/Lesson52_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
import warnings
warnings.filterwarnings("ignore")
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import sklearn.metrics as sm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.metrics import matthews_corrcoef, balanced_accuracy_score, cohen_kappa_score

In [77]:
data = load_iris()
X=data.data
y=data.target
X_train, X_val, y_train, y_val = train_test_split(X, y, train_size=0.8, random_state=44)

print(X_train.shape,X.shape)

(120, 4) (150, 4)


In [78]:
model = GaussianNB()
model.fit(X_train, y_train)


GaussianNB()

In [80]:
y_predict=model.predict(X_val)

m_sc=model.score(X_val, y_val)
print('Model.score = ',m_sc)

accuracy=sm.accuracy_score(y_val,y_predict)
print('Accuracy = ', accuracy)

precision_score=sm.precision_score(y_val,y_predict, average='macro')
print('Precision_score = ', precision_score)

recall_score=sm.recall_score(y_val, y_predict, average='micro')
print('Recall_score =', recall_score)

f1_score=sm.f1_score(y_val, y_predict, average='weighted')
print('F1 score = ', f1_score)

mcc = sm.matthews_corrcoef(y_val, y_predict)
print('Matthews_corrcoef = ', mcc)

balanced_acc = sm.balanced_accuracy_score(y_val, y_predict)
print('Balanced_acc = ', balanced_acc)

kappa = sm.cohen_kappa_score(y_val, y_predict)
print('Cohen_kappa_score = ', kappa)

confusion_matrix=sm.confusion_matrix(y_val, y_predict)
print('Confusion_matrix \n', confusion_matrix)

Model.score =  0.9333333333333333
Accuracy =  0.9333333333333333
Precision_score =  0.9351851851851851
Recall_score = 0.9333333333333333
F1 score =  0.9333333333333333
Matthews_corrcoef =  0.898989898989899
Balanced_acc =  0.9351851851851851
Cohen_kappa_score =  0.898989898989899
Confusion_matrix 
 [[ 9  0  0]
 [ 0  8  1]
 [ 0  1 11]]
